In [8]:
import tensorflow as tf
print("Tensorflow version:", tf.__version__)

Tensorflow version: 2.18.0


This is the part of the code that has the important information regarding the way that we store the load data, and prepares a dataset

In [9]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

The cell below takes the way that I can layer cells and make it so that each layer has a corresponding input and output tensor

In [10]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [11]:
predictions = model(x_train[:1]).numpy()
predictions
tf.nn.softmax(predictions).numpy()

array([[0.09048174, 0.08077037, 0.0557828 , 0.10896753, 0.14021736,
        0.05402163, 0.0766298 , 0.12099948, 0.05552528, 0.21660405]],
      dtype=float32)

Define the loss function and make sure that it is trained, and that it takes the correct vectors of logic and can return the average loss

In [12]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1], predictions).numpy()

2.9183707

What this does is take the information from the model and ensure that the right amount of epochs and accuracy are put into the model in order to make an optimized compilation of the data

In [13]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])
model.fit(x_train, y_train, epochs=5)
model.evaluate(x_test,  y_test, verbose=2)
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])
probability_model(x_test[:5])

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.8617 - loss: 0.4736
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9568 - loss: 0.1464
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9668 - loss: 0.1076
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9726 - loss: 0.0872
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9782 - loss: 0.0712
313/313 - 1s - 2ms/step - accuracy: 0.9775 - loss: 0.0750


<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.6123165e-08, 5.2087927e-07, 4.2073301e-05, 1.7914940e-04,
        5.4995616e-11, 8.2560956e-07, 2.2519328e-11, 9.9977320e-01,
        2.6892644e-07, 3.8680028e-06],
       [6.0413078e-07, 4.1011783e-05, 9.9995232e-01, 5.2492928e-06,
        7.7879081e-15, 7.8197775e-07, 4.6117183e-08, 1.7901173e-15,
        1.8429226e-08, 6.6324225e-14],
       [9.3255130e-06, 9.9541712e-01, 1.0455844e-03, 4.0795461e-05,
        1.7233381e-04, 2.3108421e-05, 3.8206772e-04, 1.5445127e-03,
        1.3537052e-03, 1.1351569e-05],
       [9.9935442e-01, 1.6668123e-07, 4.5161534e-04, 7.6584649e-07,
        2.0562029e-06, 1.3747970e-05, 1.5760378e-04, 7.1218997e-06,
        5.2308934e-07, 1.2044844e-05],
       [1.0820802e-06, 5.1068492e-09, 5.2577641e-05, 5.1259786e-08,
        9.9699712e-01, 1.4377953e-06, 7.4744476e-06, 5.8153433e-05,
        1.2151250e-07, 2.8820387e-03]], dtype=float32)>